export const CREATE_PUPPY_SUCCESS = 'CREATE_PUPPY_SUCCESS';
export const READ_PUPPIES_SUCCESS = 'READ_PUPPIES_SUCCESS';
export const UPDATE_PUPPY_SUCCESS = 'UPDATE_PUPPY_SUCCESS';
export const DELETE_PUPPY_SUCCESS = 'DELETE_PUPPY_SUCCESS';
