export const GET_PUPPIES_SUCCESS = 'GET_PUPPIES_SUCCESS';
export const ADD_PUPPY_SUCCESS = 'ADD_PUPPY_SUCCESS';
export const DELETE_PUPPY_SUCCESS = 'DELETE_PUPPY_SUCCESS';
export const ADOPT_PUPPY_SUCCESS = 'ADOPT_PUPPY_SUCCESS';
export const GENERIC_ACTION_ERROR = 'GENERIC_ACTION_ERROR';
export const FILTER_PUPPIES = 'FILTER_PUPPIES';
